name: Bug report
description: Something is not working correctly.
title: "[BUG]"
labels: "bug, to be solved"

body:
  - type: checkboxes
    attributes:
      label: Get started
      options:
        - label: >-
            I have read [Contributing guidelines](https://github.com/cainmagi/FFmpeg-Encoder-Decoder-for-Python/blob/master/CONTRIBUTING.md).
          required: true
        - label: >-
            I have confirmed that my problem could not be solved by the [troubleshooting](https://cainmagi.github.io/FFmpeg-Encoder-Decoder-for-Python/docs/troubleshooting/installation) section in the documentation.
          required: true
        - label: >-
            I agree to follow the [Code of Conduct](https://github.com/cainmagi/FFmpeg-Encoder-Decoder-for-Python/blob/master/CODE_OF_CONDUCT.md).
          required: true
        - label: >-
            I have confirmed that my issue is not duplicated with an existing issue.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: >-
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: >-
        Steps to reproduce the behavior. Instead of describing the steps, you could also provide your codes related to the error here.
      value: |
        1. Get package from '...'
        2. Then run '...'
        3. An error occurs.

  - type: textarea
    attributes:
      label: Traceback
      description: >-
        The python trackback of the bug. If there is no traceback, please describe (1) The expected behaviors. (2) The actual behaviors.
      render: sh-session

  - type: textarea
    attributes:
      label: Behaviors
      description: >-
        If there is no traceback, please describe (1) The expected behaviors. (2) The actual behaviors.
      value: |
        1. The expected behaviors:
        2. The actual behaviors:

  - type: textarea
    attributes:
      label: Screenshots
      description: >-
        If applicable, add screenshots to help explain your problem.

  - type: input
    attributes:
      label: OS
      description: >-
        e.g. Ubuntu 20.04, Debian 10, Windows 10 21H1
    validations:
      required: true
  - type: input
    attributes:
      label: Python version
      description: >-
        e.g. 3.8
    validations:
      required: true
  - type: input
    attributes:
      label: numpy version
      description: >-
        e.g. 1.21.1
    validations:
      required: true
  - type: input
    attributes:
      label: mpegCoder version
      description: >-
        e.g. 3.1.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: >-
        Add any other context about the problem here.
