# This workflow will deploy the documentation.
# For more information see: https://docusaurus.io/zh-CN/docs/deployment

name: docusaurus

on:
  pull_request:
    branches:
     - docs
  push:
    branches:
     - docs

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - name: Test Build
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
            yarn run build
          else
            if [ -e package-lock.json ]; then
              npm ci
            else
              npm i
            fi
            npm run build
          fi
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - name: Release to GitHub Pages
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
            yarn run build
          else
            if [ -e package-lock.json ]; then
              npm ci
            else
              npm i
            fi
            npm run build
          fi
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
          token: ${{ secrets.GH_PAGES_TOKEN }}
          git-config-name: cainmagi
          git-config-email: cainmagi@gmail.com
